-- ==========================================
-- 1. NETTOYAGE (Optionnel - à utiliser avec précaution)
-- ==========================================
-- DROP TABLE IF EXISTS public.user_passions;
-- DROP TABLE IF EXISTS public.user_languages;
-- DROP TABLE IF EXISTS public.user_skills;
-- DROP TABLE IF EXISTS public.projects;
-- DROP TABLE IF EXISTS public.skill_refs;
-- DROP TABLE IF EXISTS public.profiles;

-- ==========================================
-- 2. TABLES PRINCIPALES
-- ==========================================

-- PROFILES
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  email TEXT,
  nom TEXT,
  prenom TEXT,
  role TEXT CHECK (role IN ('Enseignant', 'Technicien', 'Eco-delegue', 'Association', 'Administrateur')),
  badge_verified BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- SKILL REFS (Référentiel de compétences)
CREATE TABLE IF NOT EXISTS public.skill_refs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  category TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- PROJECTS
CREATE TABLE IF NOT EXISTS public.projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT,
  impact_carbone NUMERIC DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- USER SKILLS
CREATE TABLE IF NOT EXISTS public.user_skills (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  skill_name TEXT NOT NULL,
  level TEXT CHECK (level IN ('Débutant', 'Intermédiaire', 'Expert')),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- USER LANGUAGES
CREATE TABLE IF NOT EXISTS public.user_languages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  language TEXT NOT NULL,
  level TEXT CHECK (level IN ('Débutant', 'Intermédiaire', 'Courant', 'Expert', 'Bilingue', 'Natif')),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- USER PASSIONS
CREATE TABLE IF NOT EXISTS public.user_passions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  passion TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==========================================
-- 3. SECURITE (ROW LEVEL SECURITY)
-- ==========================================

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.skill_refs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_skills ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_languages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_passions ENABLE ROW LEVEL SECURITY;

-- Policies PROFILES
CREATE POLICY "Public profiles are viewable by everyone" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Users can update own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- Policies PROJECTS
CREATE POLICY "Public projects are viewable by everyone" ON public.projects FOR SELECT USING (true);
CREATE POLICY "Users can insert own projects" ON public.projects FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own projects" ON public.projects FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own projects" ON public.projects FOR DELETE USING (auth.uid() = user_id);

-- Policies SKILL_REFS
CREATE POLICY "Public skills are viewable by everyone" ON public.skill_refs FOR SELECT USING (true);

-- Policies USER_SKILLS
CREATE POLICY "Public user_skills are viewable by everyone" ON public.user_skills FOR SELECT USING (true);
CREATE POLICY "Users can insert own skills" ON public.user_skills FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can delete own skills" ON public.user_skills FOR DELETE USING (auth.uid() = user_id);

-- Policies USER_LANGUAGES
CREATE POLICY "Public languages" ON public.user_languages FOR SELECT USING (true);
CREATE POLICY "Insert own languages" ON public.user_languages FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Delete own languages" ON public.user_languages FOR DELETE USING (auth.uid() = user_id);

-- Policies USER_PASSIONS
CREATE POLICY "Public passions" ON public.user_passions FOR SELECT USING (true);
CREATE POLICY "Insert own passions" ON public.user_passions FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Delete own passions" ON public.user_passions FOR DELETE USING (auth.uid() = user_id);

-- ==========================================
-- 4. AUTOMATISATION (TRIGGER)
-- ==========================================

-- Fonction pour créer un profil automatiquement à l'inscription
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, email, nom, prenom, role)
  VALUES (
    new.id,
    new.email,
    new.raw_user_meta_data->>'nom',
    new.raw_user_meta_data->>'prenom',
    new.raw_user_meta_data->>'role'
  );
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- ==========================================
-- 5. FONCTION RPC (Inscription Complète)
-- ==========================================

-- Cette fonction permet de mettre à jour le profil et d'ajouter toutes les infos en une seule fois
-- Elle contourne les problèmes de RLS côté client lors de l'inscription
CREATE OR REPLACE FUNCTION public.update_full_profile(
  p_nom TEXT,
  p_prenom TEXT,
  p_role TEXT,
  p_skills JSONB,
  p_languages JSONB,
  p_passions JSONB,
  p_projects JSONB
)
RETURNS VOID AS $$
DECLARE
  v_user_id UUID;
BEGIN
  -- Récupérer l'ID de l'utilisateur courant
  v_user_id := auth.uid();
  
  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'Non authentifié';
  END IF;

  -- 1. Mettre à jour le profil
  UPDATE public.profiles
  SET nom = p_nom, prenom = p_prenom, role = p_role, updated_at = NOW()
  WHERE id = v_user_id;

  -- 2. Insérer les compétences
  IF p_skills IS NOT NULL AND jsonb_array_length(p_skills) > 0 THEN
    INSERT INTO public.user_skills (user_id, skill_name, level)
    SELECT v_user_id, value->>'skill_name', value->>'level'
    FROM jsonb_array_elements(p_skills);
  END IF;

  -- 3. Insérer les langues
  IF p_languages IS NOT NULL AND jsonb_array_length(p_languages) > 0 THEN
    INSERT INTO public.user_languages (user_id, language, level)
    SELECT v_user_id, value->>'language', value->>'level'
    FROM jsonb_array_elements(p_languages);
  END IF;

  -- 4. Insérer les passions
  IF p_passions IS NOT NULL AND jsonb_array_length(p_passions) > 0 THEN
    INSERT INTO public.user_passions (user_id, passion)
    SELECT v_user_id, value->>'passion'
    FROM jsonb_array_elements(p_passions);
  END IF;

  -- 5. Insérer les projets
  IF p_projects IS NOT NULL AND jsonb_array_length(p_projects) > 0 THEN
    INSERT INTO public.projects (user_id, title, description, impact_carbone)
    SELECT v_user_id, value->>'title', value->>'description', (value->>'impact_carbone')::numeric
    FROM jsonb_array_elements(p_projects);
  END IF;

END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
